### ISSUE TITLE
decrement lower bound?

### ISSUE THREAD

**Issue by matthiasmullie** [dragoonis/psr-simplecache#2]
Memcached, for example, won't decrement below 0 (http://php.net/manual/en/memcached.decrement.php)
In such case, should `false` (can't decrement) or `0` (current counter value) be returned?
Or should the implementing library work around any native bounds to keep decrementing beyond such limits?

**Comment by Seldaek** [comment]
IMO it's ok if you pick such a cache backend that you have to live with its limitations. Negative counters are probably enough of an edge case that this won't matter in practice, but anyway I wouldn't want to limit the spec because of memcache's failures..

**Comment by matthiasmullie** [comment]
Fair enough, that's clear!
