### ISSUE TITLE
TTL (as int): only relative, or also absolute?

### ISSUE THREAD

**Issue by matthiasmullie** [dragoonis/psr-simplecache#3]
Memcached, for example, accepts both relative and absolute TTLs (http://php.net/manual/en/memcached.expiration.php)

Are only relative TTL integers allowed, or also absolute timestamps at which the cache should expire?

It's pretty easy to implement both, as long as we know the exact rules :)

**Comment by Seldaek** [comment]
Right now the spec only includes relative TTL and DateInterval, which is inherited from PSR-6's TTL spec. We just didn't include the absolute "Expiration" bit to keep things simpler. I think we could also support a DateTime expiration but not sure if there are any gotchas there. @dragoonis @mindplay-dk @nicolas-grekas any thoughts?

**Comment by matthiasmullie** [comment]
Might as well want to leave it as relative-only then (which is implied by "time to live" anyway), or people are going to get confused about integer input (is it relative, absolute, or both)

**Comment by Seldaek** [comment]
Yeah true, less confusion possible that way. Feel free to close I don't have access here :)

**Comment by mindplay-dk** [comment]
> I think we could also support a DateTime expiration but not sure if there are any gotchas there

There's a pretty big gotcha, which is the potential for differences in terms of local/remote system clocks.

Being able to specify an absolute timestamp, you can end up in dangerous scenarios where everything expires immediately because of, say, a two-hour time-difference between the local PHP server and a remote MySQL server.

Relative time is much safer in that regard.

**Comment by dragoonis** [comment]
I agree with the gotchyas outlined above and we won't be adding in a specific DateTime timestamp, but keep things relative, as they currently are.

@mindplay-dk @matthiasmullie @Seldaek
