### ISSUE TITLE
What about negative TTLs?

### ISSUE THREAD

**Issue by matthiasmullie** [dragoonis/psr-simplecache#4]
Are negative TTLs allowed, and if so, how should they be treated?

Couchbase, for example, bails on negative TTL (invalid input)
Redis, IIRC, has not proper documented behavior and has been seen to just ignore them.
Some others will immediately expire keys with negative TTL (effective `->delete()`ing them)

Should negative TTLs (if allowed) return a `false` (nothing has been stored) or `true` (your operation was successful, but it has already expired)

**Comment by Seldaek** [comment]
Negative TTLs are a sort of misuse IMO so I'd be ok with throwing InvalidArgumentException or just returning true after a noop. /cc @dragoonis @mindplay-dk @nicolas-grekas

**Comment by nicolas-grekas** [comment]
Negative expiration == delete in psr-6, because it forbids throwing exception except for the documented cases.

**Comment by Seldaek** [comment]
OK I'll add this to the PSR-16 spec then for clarity. Please see also #11 (I added mentions in an edit, not sure if it notifies in that case).

**Comment by Seldaek** [comment]
Done in https://github.com/php-fig/fig-standards/pull/838/commits/b056e71d3c287126a66eabd00bcbf415b8c22802
